# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pm_view.ui'
#
# Created by: PyQt5 UI code generator 5.8
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PM_View(object):
    def setupUi(self, PM_View):
        PM_View.setObjectName("PM_View")
        PM_View.resize(793, 600)
        self.centralwidget = QtWidgets.QWidget(PM_View)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.test_label = QtWidgets.QLabel(self.centralwidget)
        self.test_label.setObjectName("test_label")
        self.verticalLayout.addWidget(self.test_label)
        self.testList = QtWidgets.QListView(self.centralwidget)
        self.testList.setObjectName("testList")
        self.verticalLayout.addWidget(self.testList)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setObjectName("addButton")
        self.verticalLayout_3.addWidget(self.addButton)
        self.removeButtion = QtWidgets.QPushButton(self.centralwidget)
        self.removeButtion.setObjectName("removeButtion")
        self.verticalLayout_3.addWidget(self.removeButtion)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.selected_label = QtWidgets.QLabel(self.centralwidget)
        self.selected_label.setObjectName("selected_label")
        self.verticalLayout_2.addWidget(self.selected_label)
        self.selectedView = QtWidgets.QListView(self.centralwidget)
        self.selectedView.setObjectName("selectedView")
        self.verticalLayout_2.addWidget(self.selectedView)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(348, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.saveButton = QtWidgets.QPushButton(self.centralwidget)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout.addWidget(self.saveButton)
        self.cancelButtion = QtWidgets.QPushButton(self.centralwidget)
        self.cancelButtion.setObjectName("cancelButtion")
        self.horizontalLayout.addWidget(self.cancelButtion)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        PM_View.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PM_View)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 793, 28))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuTest = QtWidgets.QMenu(self.menubar)
        self.menuTest.setObjectName("menuTest")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        PM_View.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PM_View)
        self.statusbar.setObjectName("statusbar")
        PM_View.setStatusBar(self.statusbar)
        self.actionReset = QtWidgets.QAction(PM_View)
        self.actionReset.setObjectName("actionReset")
        self.menuFile.addAction(self.actionReset)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuTest.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(PM_View)
        QtCore.QMetaObject.connectSlotsByName(PM_View)

    def retranslateUi(self, PM_View):
        _translate = QtCore.QCoreApplication.translate
        PM_View.setWindowTitle(_translate("PM_View", "PM_View"))
        self.test_label.setText(_translate("PM_View", "Test List:"))
        self.addButton.setText(_translate("PM_View", "Add"))
        self.removeButtion.setText(_translate("PM_View", "Remove"))
        self.selected_label.setText(_translate("PM_View", "Selected List:"))
        self.saveButton.setText(_translate("PM_View", "Save"))
        self.cancelButtion.setText(_translate("PM_View", "Cancel"))
        self.menuFile.setTitle(_translate("PM_View", "File"))
        self.menuTest.setTitle(_translate("PM_View", "Test"))
        self.menuHelp.setTitle(_translate("PM_View", "Help"))
        self.actionReset.setText(_translate("PM_View", "Reset"))

