# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\private_work\p4KuaiSync\MyUtils\maya_script\BevelTool/src/Qt/UI/MWBevelToolMainWindow.ui'
#
# Created: Fri Feb 02 14:56:34 2018
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MWBevelToolMainWindow(object):
    def setupUi(self, MWBevelToolMainWindow):
        MWBevelToolMainWindow.setObjectName("MWBevelToolMainWindow")
        MWBevelToolMainWindow.resize(876, 799)
        self.centralwidget = QtWidgets.QWidget(MWBevelToolMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.toolbarGroupBox = QtWidgets.QGroupBox(self.splitter)
        self.toolbarGroupBox.setTitle("")
        self.toolbarGroupBox.setFlat(True)
        self.toolbarGroupBox.setCheckable(False)
        self.toolbarGroupBox.setObjectName("toolbarGroupBox")
        self.bevelSetTreeView = QtWidgets.QTreeView(self.splitter)
        self.bevelSetTreeView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.bevelSetTreeView.setTextElideMode(QtCore.Qt.ElideNone)
        self.bevelSetTreeView.setIndentation(0)
        self.bevelSetTreeView.setWordWrap(False)
        self.bevelSetTreeView.setObjectName("bevelSetTreeView")
        self.bevelSetTreeView.header().setMinimumSectionSize(50)
        self.gridLayout_2.addWidget(self.splitter, 0, 0, 1, 1)
        MWBevelToolMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MWBevelToolMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 876, 21))
        self.menubar.setObjectName("menubar")
        self.editMenu = QtWidgets.QMenu(self.menubar)
        self.editMenu.setObjectName("editMenu")
        self.viewMenu = QtWidgets.QMenu(self.menubar)
        self.viewMenu.setObjectName("viewMenu")
        MWBevelToolMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MWBevelToolMainWindow)
        self.statusbar.setObjectName("statusbar")
        MWBevelToolMainWindow.setStatusBar(self.statusbar)
        self.controlDock = QtWidgets.QDockWidget(MWBevelToolMainWindow)
        self.controlDock.setMinimumSize(QtCore.QSize(280, 503))
        self.controlDock.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.controlDock.setObjectName("controlDock")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.bevelSetLabel = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.bevelSetLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.bevelSetLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.bevelSetLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bevelSetLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.bevelSetLabel.setTextFormat(QtCore.Qt.RichText)
        self.bevelSetLabel.setWordWrap(False)
        self.bevelSetLabel.setIndent(20)
        self.bevelSetLabel.setObjectName("bevelSetLabel")
        self.verticalLayout_3.addWidget(self.bevelSetLabel)
        self.bevelSetGroupBox = QtWidgets.QGroupBox(self.dockWidgetContents_2)
        self.bevelSetGroupBox.setTitle("")
        self.bevelSetGroupBox.setFlat(True)
        self.bevelSetGroupBox.setCheckable(False)
        self.bevelSetGroupBox.setObjectName("bevelSetGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.bevelSetGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.newBevelSetButton = QtWidgets.QPushButton(self.bevelSetGroupBox)
        self.newBevelSetButton.setObjectName("newBevelSetButton")
        self.gridLayout.addWidget(self.newBevelSetButton, 0, 0, 1, 1)
        self.addMemberButton = QtWidgets.QPushButton(self.bevelSetGroupBox)
        self.addMemberButton.setObjectName("addMemberButton")
        self.gridLayout.addWidget(self.addMemberButton, 0, 1, 1, 1)
        self.removeMemberButton = QtWidgets.QPushButton(self.bevelSetGroupBox)
        self.removeMemberButton.setObjectName("removeMemberButton")
        self.gridLayout.addWidget(self.removeMemberButton, 1, 0, 1, 1)
        self.deleteBevelSetbutton = QtWidgets.QPushButton(self.bevelSetGroupBox)
        self.deleteBevelSetbutton.setObjectName("deleteBevelSetbutton")
        self.gridLayout.addWidget(self.deleteBevelSetbutton, 1, 1, 1, 1)
        self.verticalLayout_3.addWidget(self.bevelSetGroupBox)
        self.bevelLabel = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.bevelLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.bevelLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.bevelLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bevelLabel.setTextFormat(QtCore.Qt.RichText)
        self.bevelLabel.setIndent(20)
        self.bevelLabel.setObjectName("bevelLabel")
        self.verticalLayout_3.addWidget(self.bevelLabel)
        self.bevelGroupBox = QtWidgets.QGroupBox(self.dockWidgetContents_2)
        self.bevelGroupBox.setTitle("")
        self.bevelGroupBox.setFlat(True)
        self.bevelGroupBox.setObjectName("bevelGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.bevelGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.memberButton = QtWidgets.QPushButton(self.bevelGroupBox)
        self.memberButton.setObjectName("memberButton")
        self.verticalLayout_2.addWidget(self.memberButton)
        self.bevelButton = QtWidgets.QPushButton(self.bevelGroupBox)
        self.bevelButton.setObjectName("bevelButton")
        self.verticalLayout_2.addWidget(self.bevelButton)
        self.verticalLayout_3.addWidget(self.bevelGroupBox)
        self.bevelOptionsLabel = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.bevelOptionsLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.bevelOptionsLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.bevelOptionsLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bevelOptionsLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.bevelOptionsLabel.setTextFormat(QtCore.Qt.RichText)
        self.bevelOptionsLabel.setIndent(20)
        self.bevelOptionsLabel.setObjectName("bevelOptionsLabel")
        self.verticalLayout_3.addWidget(self.bevelOptionsLabel)
        self.bevelOptionsGroupBox = QtWidgets.QGroupBox(self.dockWidgetContents_2)
        self.bevelOptionsGroupBox.setTitle("")
        self.bevelOptionsGroupBox.setFlat(True)
        self.bevelOptionsGroupBox.setObjectName("bevelOptionsGroupBox")
        self.verticalLayout_3.addWidget(self.bevelOptionsGroupBox)
        self.selectionLabel = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.selectionLabel.setMinimumSize(QtCore.QSize(0, 20))
        self.selectionLabel.setMaximumSize(QtCore.QSize(16777215, 30))
        self.selectionLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.selectionLabel.setFrameShadow(QtWidgets.QFrame.Plain)
        self.selectionLabel.setTextFormat(QtCore.Qt.RichText)
        self.selectionLabel.setIndent(20)
        self.selectionLabel.setObjectName("selectionLabel")
        self.verticalLayout_3.addWidget(self.selectionLabel)
        self.selectionGroupBox = QtWidgets.QGroupBox(self.dockWidgetContents_2)
        self.selectionGroupBox.setTitle("")
        self.selectionGroupBox.setFlat(True)
        self.selectionGroupBox.setObjectName("selectionGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.selectionGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.selectMembersButton = QtWidgets.QPushButton(self.selectionGroupBox)
        self.selectMembersButton.setObjectName("selectMembersButton")
        self.verticalLayout.addWidget(self.selectMembersButton)
        self.selectHardEdgesButton = QtWidgets.QPushButton(self.selectionGroupBox)
        self.selectHardEdgesButton.setObjectName("selectHardEdgesButton")
        self.verticalLayout.addWidget(self.selectHardEdgesButton)
        self.selectSoftEdgesButton = QtWidgets.QPushButton(self.selectionGroupBox)
        self.selectSoftEdgesButton.setObjectName("selectSoftEdgesButton")
        self.verticalLayout.addWidget(self.selectSoftEdgesButton)
        self.smoothingAngleCheckBox = QtWidgets.QCheckBox(self.selectionGroupBox)
        self.smoothingAngleCheckBox.setObjectName("smoothingAngleCheckBox")
        self.verticalLayout.addWidget(self.smoothingAngleCheckBox)
        self.smoothingAngleSlider = QtWidgets.QSlider(self.selectionGroupBox)
        self.smoothingAngleSlider.setEnabled(False)
        self.smoothingAngleSlider.setMaximum(1800000)
        self.smoothingAngleSlider.setProperty("value", 300000)
        self.smoothingAngleSlider.setOrientation(QtCore.Qt.Horizontal)
        self.smoothingAngleSlider.setObjectName("smoothingAngleSlider")
        self.verticalLayout.addWidget(self.smoothingAngleSlider)
        self.smoothingAngleSpinBox = QtWidgets.QDoubleSpinBox(self.selectionGroupBox)
        self.smoothingAngleSpinBox.setEnabled(False)
        self.smoothingAngleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.smoothingAngleSpinBox.setDecimals(4)
        self.smoothingAngleSpinBox.setMaximum(180.0)
        self.smoothingAngleSpinBox.setProperty("value", 30.0)
        self.smoothingAngleSpinBox.setObjectName("smoothingAngleSpinBox")
        self.verticalLayout.addWidget(self.smoothingAngleSpinBox)
        self.verticalLayout_3.addWidget(self.selectionGroupBox)
        spacerItem = QtWidgets.QSpacerItem(20, 409, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.controlDock.setWidget(self.dockWidgetContents_2)
        MWBevelToolMainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.controlDock)
        self.menubar.addAction(self.editMenu.menuAction())
        self.menubar.addAction(self.viewMenu.menuAction())

        self.retranslateUi(MWBevelToolMainWindow)
        QtCore.QMetaObject.connectSlotsByName(MWBevelToolMainWindow)

    def retranslateUi(self, MWBevelToolMainWindow):
        MWBevelToolMainWindow.setWindowTitle(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Mindwalk Bevel Tool", None, -1))
        self.editMenu.setTitle(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Edit", None, -1))
        self.viewMenu.setTitle(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "View", None, -1))
        self.controlDock.setWindowTitle(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Control Panel", None, -1))
        self.bevelSetLabel.setText(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Bevel Set</span></p></body></html>", None, -1))
        self.newBevelSetButton.setText(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "New", None, -1))
        self.addMemberButton.setText(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Add", None, -1))
        self.removeMemberButton.setText(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Remove", None, -1))
        self.deleteBevelSetbutton.setText(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Delete", None, -1))
        self.bevelLabel.setText(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Bevel</span></p></body></html>", None, -1))
        self.memberButton.setText(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Show members", None, -1))
        self.bevelButton.setText(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Bevel", None, -1))
        self.bevelOptionsLabel.setText(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Bevel Options</span></p></body></html>", None, -1))
        self.selectionLabel.setText(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Selection</span></p></body></html>", None, -1))
        self.selectMembersButton.setText(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Select Members", None, -1))
        self.selectHardEdgesButton.setText(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Select Hard Edges", None, -1))
        self.selectSoftEdgesButton.setText(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Select Soft Edges", None, -1))
        self.smoothingAngleCheckBox.setText(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Smoothing angle", None, -1))

