# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\private_work\p4KuaiSync\MyUtils\maya_script\BevelTool/src/Qt/UI/MWBevelToolMainWindow_io.ui'
#
# Created: Mon Apr 09 17:58:08 2018
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MWBevelToolMainWindow(object):
    def setupUi(self, MWBevelToolMainWindow):
        MWBevelToolMainWindow.setObjectName("MWBevelToolMainWindow")
        MWBevelToolMainWindow.resize(935, 821)
        self.centralwidget = QtWidgets.QWidget(MWBevelToolMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.bevelSetTreeView = QtWidgets.QTreeView(self.centralwidget)
        self.bevelSetTreeView.setMinimumSize(QtCore.QSize(0, 251))
        self.bevelSetTreeView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.bevelSetTreeView.setTextElideMode(QtCore.Qt.ElideNone)
        self.bevelSetTreeView.setIndentation(0)
        self.bevelSetTreeView.setWordWrap(False)
        self.bevelSetTreeView.setObjectName("bevelSetTreeView")
        self.bevelSetTreeView.header().setMinimumSectionSize(50)
        self.verticalLayout_5.addWidget(self.bevelSetTreeView)
        MWBevelToolMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MWBevelToolMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 935, 21))
        self.menubar.setObjectName("menubar")
        self.editMenu = QtWidgets.QMenu(self.menubar)
        self.editMenu.setObjectName("editMenu")
        self.viewMenu = QtWidgets.QMenu(self.menubar)
        self.viewMenu.setObjectName("viewMenu")
        self.selectionMenu = QtWidgets.QMenu(self.menubar)
        self.selectionMenu.setObjectName("selectionMenu")
        MWBevelToolMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MWBevelToolMainWindow)
        self.statusbar.setObjectName("statusbar")
        MWBevelToolMainWindow.setStatusBar(self.statusbar)
        self.bevelToolbar = QtWidgets.QToolBar(MWBevelToolMainWindow)
        self.bevelToolbar.setMovable(True)
        self.bevelToolbar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.bevelToolbar.setFloatable(False)
        self.bevelToolbar.setObjectName("bevelToolbar")
        MWBevelToolMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.bevelToolbar)
        self.selectionToolbar = QtWidgets.QToolBar(MWBevelToolMainWindow)
        self.selectionToolbar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.selectionToolbar.setObjectName("selectionToolbar")
        MWBevelToolMainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.selectionToolbar)
        self.selectionConstraintDock = QtWidgets.QDockWidget(MWBevelToolMainWindow)
        self.selectionConstraintDock.setMinimumSize(QtCore.QSize(280, 508))
        self.selectionConstraintDock.setObjectName("selectionConstraintDock")
        self.dockWidgetContents_2 = QtWidgets.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.selectionLabel = QtWidgets.QLabel(self.dockWidgetContents_2)
        self.selectionLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.selectionLabel.setObjectName("selectionLabel")
        self.verticalLayout_4.addWidget(self.selectionLabel)
        self.selectionConstraintGroupBox = QtWidgets.QGroupBox(self.dockWidgetContents_2)
        self.selectionConstraintGroupBox.setTitle("")
        self.selectionConstraintGroupBox.setFlat(True)
        self.selectionConstraintGroupBox.setObjectName("selectionConstraintGroupBox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.selectionConstraintGroupBox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.selectHardEdgesButton = QtWidgets.QPushButton(self.selectionConstraintGroupBox)
        self.selectHardEdgesButton.setObjectName("selectHardEdgesButton")
        self.verticalLayout_3.addWidget(self.selectHardEdgesButton)
        self.selectSoftEdgesButton = QtWidgets.QPushButton(self.selectionConstraintGroupBox)
        self.selectSoftEdgesButton.setObjectName("selectSoftEdgesButton")
        self.verticalLayout_3.addWidget(self.selectSoftEdgesButton)
        self.smoothingAngleCheckBox = QtWidgets.QCheckBox(self.selectionConstraintGroupBox)
        self.smoothingAngleCheckBox.setObjectName("smoothingAngleCheckBox")
        self.verticalLayout_3.addWidget(self.smoothingAngleCheckBox)
        self.smoothingAngleSlider = QtWidgets.QSlider(self.selectionConstraintGroupBox)
        self.smoothingAngleSlider.setEnabled(False)
        self.smoothingAngleSlider.setMaximum(1800000)
        self.smoothingAngleSlider.setProperty("value", 300000)
        self.smoothingAngleSlider.setOrientation(QtCore.Qt.Horizontal)
        self.smoothingAngleSlider.setObjectName("smoothingAngleSlider")
        self.verticalLayout_3.addWidget(self.smoothingAngleSlider)
        self.smoothingAngleSpinBox = QtWidgets.QDoubleSpinBox(self.selectionConstraintGroupBox)
        self.smoothingAngleSpinBox.setEnabled(False)
        self.smoothingAngleSpinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.smoothingAngleSpinBox.setDecimals(4)
        self.smoothingAngleSpinBox.setMaximum(180.0)
        self.smoothingAngleSpinBox.setProperty("value", 30.0)
        self.smoothingAngleSpinBox.setObjectName("smoothingAngleSpinBox")
        self.verticalLayout_3.addWidget(self.smoothingAngleSpinBox)
        self.verticalLayout_4.addWidget(self.selectionConstraintGroupBox)
        spacerItem = QtWidgets.QSpacerItem(20, 289, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.selectionConstraintDock.setWidget(self.dockWidgetContents_2)
        MWBevelToolMainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.selectionConstraintDock)
        self.finishBevelAction = QtWidgets.QAction(MWBevelToolMainWindow)
        self.finishBevelAction.setObjectName("finishBevelAction")
        self.displayDrawOverrideAttrAction = QtWidgets.QAction(MWBevelToolMainWindow)
        self.displayDrawOverrideAttrAction.setObjectName("displayDrawOverrideAttrAction")
        self.actionCreate_a_Bevel_Set = QtWidgets.QAction(MWBevelToolMainWindow)
        self.actionCreate_a_Bevel_Set.setObjectName("actionCreate_a_Bevel_Set")
        self.actionMove_Edges_into_New_Bevel_Set = QtWidgets.QAction(MWBevelToolMainWindow)
        self.actionMove_Edges_into_New_Bevel_Set.setObjectName("actionMove_Edges_into_New_Bevel_Set")
        self.actionCreate = QtWidgets.QAction(MWBevelToolMainWindow)
        self.actionCreate.setObjectName("actionCreate")
        self.moveAction = QtWidgets.QAction(MWBevelToolMainWindow)
        self.moveAction.setCheckable(True)
        self.moveAction.setObjectName("moveAction")
        self.maintainAction = QtWidgets.QAction(MWBevelToolMainWindow)
        self.maintainAction.setCheckable(True)
        self.maintainAction.setObjectName("maintainAction")
        self.chooseAction = QtWidgets.QAction(MWBevelToolMainWindow)
        self.chooseAction.setCheckable(True)
        self.chooseAction.setChecked(True)
        self.chooseAction.setObjectName("chooseAction")
        self.displayOverrideAction = QtWidgets.QAction(MWBevelToolMainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("."), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.displayOverrideAction.setIcon(icon)
        self.displayOverrideAction.setObjectName("displayOverrideAction")
        self.newAction = QtWidgets.QAction(MWBevelToolMainWindow)
        self.newAction.setEnabled(False)
        self.newAction.setStatusTip("")
        self.newAction.setObjectName("newAction")
        self.addAction = QtWidgets.QAction(MWBevelToolMainWindow)
        self.addAction.setEnabled(False)
        self.addAction.setStatusTip("")
        self.addAction.setObjectName("addAction")
        self.removeAction = QtWidgets.QAction(MWBevelToolMainWindow)
        self.removeAction.setEnabled(False)
        self.removeAction.setStatusTip("")
        self.removeAction.setObjectName("removeAction")
        self.deleteAction = QtWidgets.QAction(MWBevelToolMainWindow)
        self.deleteAction.setEnabled(True)
        self.deleteAction.setStatusTip("")
        self.deleteAction.setObjectName("deleteAction")
        self.selectHardEdgeAction = QtWidgets.QAction(MWBevelToolMainWindow)
        self.selectHardEdgeAction.setStatusTip("")
        self.selectHardEdgeAction.setObjectName("selectHardEdgeAction")
        self.selectSoftEdgeAction = QtWidgets.QAction(MWBevelToolMainWindow)
        self.selectSoftEdgeAction.setStatusTip("")
        self.selectSoftEdgeAction.setObjectName("selectSoftEdgeAction")
        self.selectMemberAction = QtWidgets.QAction(MWBevelToolMainWindow)
        self.selectMemberAction.setEnabled(True)
        self.selectMemberAction.setStatusTip("")
        self.selectMemberAction.setObjectName("selectMemberAction")
        self.displaySmoothnessPreviewAction = QtWidgets.QAction(MWBevelToolMainWindow)
        self.displaySmoothnessPreviewAction.setCheckable(True)
        self.displaySmoothnessPreviewAction.setChecked(True)
        self.displaySmoothnessPreviewAction.setEnabled(False)
        self.displaySmoothnessPreviewAction.setObjectName("displaySmoothnessPreviewAction")
        self.forceAction = QtWidgets.QAction(MWBevelToolMainWindow)
        self.forceAction.setCheckable(True)
        self.forceAction.setObjectName("forceAction")
        self.repairmenAction = QtWidgets.QAction(MWBevelToolMainWindow)
        self.repairmenAction.setObjectName("repairmenAction")
        self.editMenu.addAction(self.displayOverrideAction)
        self.editMenu.addSeparator()
        self.editMenu.addAction(self.newAction)
        self.editMenu.addAction(self.addAction)
        self.editMenu.addAction(self.removeAction)
        self.editMenu.addAction(self.selectMemberAction)
        self.editMenu.addAction(self.deleteAction)
        self.editMenu.addSeparator()
        self.editMenu.addAction(self.displaySmoothnessPreviewAction)
        self.editMenu.addAction(self.forceAction)
        self.editMenu.addAction(self.repairmenAction)
        self.selectionMenu.addAction(self.selectHardEdgeAction)
        self.selectionMenu.addAction(self.selectSoftEdgeAction)
        self.menubar.addAction(self.editMenu.menuAction())
        self.menubar.addAction(self.viewMenu.menuAction())
        self.menubar.addAction(self.selectionMenu.menuAction())

        self.retranslateUi(MWBevelToolMainWindow)
        QtCore.QMetaObject.connectSlotsByName(MWBevelToolMainWindow)

    def retranslateUi(self, MWBevelToolMainWindow):
        MWBevelToolMainWindow.setWindowTitle(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Mindwalk Bevel Tool", None, -1))
        self.editMenu.setTitle(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Edit", None, -1))
        self.viewMenu.setTitle(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "View", None, -1))
        self.selectionMenu.setTitle(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Selection", None, -1))
        self.bevelToolbar.setWindowTitle(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Bevel Set", None, -1))
        self.selectionToolbar.setWindowTitle(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Selection", None, -1))
        self.selectionConstraintDock.setWindowTitle(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Selection Constraint Box", None, -1))
        self.selectionLabel.setText(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "<html><head/><body><p><span style=\" font-weight:600;\">Select Soft/Hard Edge</span></p></body></html>", None, -1))
        self.selectHardEdgesButton.setText(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Select Hard Edges", None, -1))
        self.selectSoftEdgesButton.setText(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Select Soft Edges", None, -1))
        self.smoothingAngleCheckBox.setText(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Smoothing angle", None, -1))
        self.finishBevelAction.setText(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Finish Bevel", None, -1))
        self.displayDrawOverrideAttrAction.setText(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Display DrawOverrideAttributes", None, -1))
        self.actionCreate_a_Bevel_Set.setText(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Create a Bevel Set", None, -1))
        self.actionMove_Edges_into_New_Bevel_Set.setText(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Move Edges into New Bevel Set", None, -1))
        self.actionCreate.setText(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Create", None, -1))
        self.moveAction.setText(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Move Edges into Target Bevel Set", None, -1))
        self.maintainAction.setText(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Maintain Present Status", None, -1))
        self.chooseAction.setText(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Let User Choose", None, -1))
        self.displayOverrideAction.setText(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Draw Override", None, -1))
        self.newAction.setText(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "New", None, -1))
        self.newAction.setToolTip(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Create a bevel along the selected edges and create a bevel set containing the edges.", None, -1))
        self.newAction.setWhatsThis(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Create a bevel along the selected edges and create an objectSet Create a bevel along the selected edges and create a bevel set containing the edges. the edges.", None, -1))
        self.addAction.setText(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Add", None, -1))
        self.addAction.setToolTip(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Add the selected into the selected bevel set and bevel the edges.", None, -1))
        self.addAction.setWhatsThis(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Add the selected into the selected bevel set and bevel the edges.", None, -1))
        self.removeAction.setText(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Remove", None, -1))
        self.removeAction.setToolTip(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Remove the selected edges from a bevel set  and restore the edges.", None, -1))
        self.removeAction.setWhatsThis(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Remove the selected edges from a bevel set  and restore the edges.", None, -1))
        self.deleteAction.setText(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Delete", None, -1))
        self.deleteAction.setToolTip(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Delete the selected bevel set and restore its member edges", None, -1))
        self.deleteAction.setWhatsThis(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Delete the selected bevel set and restore its member edges", None, -1))
        self.selectHardEdgeAction.setText(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Select Hard Edge", None, -1))
        self.selectHardEdgeAction.setToolTip(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Select hard edges based on face angle.", None, -1))
        self.selectHardEdgeAction.setWhatsThis(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Select hard edges based on face angle.", None, -1))
        self.selectSoftEdgeAction.setText(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Select Soft Edge", None, -1))
        self.selectSoftEdgeAction.setToolTip(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Select soft edges based on face angle.", None, -1))
        self.selectSoftEdgeAction.setWhatsThis(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Select soft edges based on face angle.", None, -1))
        self.selectMemberAction.setText(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Select Member", None, -1))
        self.selectMemberAction.setToolTip(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Select the edges of the selected object contained by a bevel set.", None, -1))
        self.selectMemberAction.setWhatsThis(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Select the edges of the selected object contained by a bevel set.", None, -1))
        self.displaySmoothnessPreviewAction.setText(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Display Smoothness Preview", None, -1))
        self.displaySmoothnessPreviewAction.setToolTip(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Display origin object in smoothness preview.", None, -1))
        self.displaySmoothnessPreviewAction.setWhatsThis(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Display origin object in smoothness preview.", None, -1))
        self.forceAction.setText(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "Force", None, -1))
        self.repairmenAction.setText(QtWidgets.QApplication.translate("MWBevelToolMainWindow", "repairmen", None, -1))

