# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\develop\MyUtils\maya_script\CheckTool\Qt\UI\GUIforPM\DetailsWindowForPM.ui'
#
# Created: Sun Nov  5 08:41:06 2017
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_DetailsMainWindowForPm(object):
    def setupUi(self, DetailsMainWindowForPm):
        DetailsMainWindowForPm.setObjectName("DetailsMainWindowForPm")
        DetailsMainWindowForPm.resize(854, 725)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DetailsMainWindowForPm.sizePolicy().hasHeightForWidth())
        DetailsMainWindowForPm.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(DetailsMainWindowForPm)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkItemsListView = QtWidgets.QListView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkItemsListView.sizePolicy().hasHeightForWidth())
        self.checkItemsListView.setSizePolicy(sizePolicy)
        self.checkItemsListView.setResizeMode(QtWidgets.QListView.Adjust)
        self.checkItemsListView.setObjectName("checkItemsListView")
        self.horizontalLayout.addWidget(self.checkItemsListView)
        self.line = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.DetailsTabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.DetailsTabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.DetailsTabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.DetailsTabWidget.setMovable(True)
        self.DetailsTabWidget.setTabBarAutoHide(True)
        self.DetailsTabWidget.setObjectName("DetailsTabWidget")
        self.tipTab = QtWidgets.QWidget()
        self.tipTab.setObjectName("tipTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tipTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textBrowser = QtWidgets.QTextBrowser(self.tipTab)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout_2.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.DetailsTabWidget.addTab(self.tipTab, "")
        self.DetailsTab = QtWidgets.QWidget()
        self.DetailsTab.setObjectName("DetailsTab")
        self.DetailsTabWidget.addTab(self.DetailsTab, "")
        self.checkTab = QtWidgets.QWidget()
        self.checkTab.setObjectName("checkTab")
        self.DetailsTabWidget.addTab(self.checkTab, "")
        self.horizontalLayout.addWidget(self.DetailsTabWidget)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.prevButton = QtWidgets.QPushButton(self.centralwidget)
        self.prevButton.setObjectName("prevButton")
        self.horizontalLayout_2.addWidget(self.prevButton)
        self.cancelButton = QtWidgets.QPushButton(self.centralwidget)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_2.addWidget(self.cancelButton)
        self.finishButton = QtWidgets.QPushButton(self.centralwidget)
        self.finishButton.setObjectName("finishButton")
        self.horizontalLayout_2.addWidget(self.finishButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        DetailsMainWindowForPm.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(DetailsMainWindowForPm)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 854, 23))
        self.menubar.setObjectName("menubar")
        DetailsMainWindowForPm.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(DetailsMainWindowForPm)
        self.statusbar.setObjectName("statusbar")
        DetailsMainWindowForPm.setStatusBar(self.statusbar)

        self.retranslateUi(DetailsMainWindowForPm)
        self.DetailsTabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(DetailsMainWindowForPm)

    def retranslateUi(self, DetailsMainWindowForPm):
        DetailsMainWindowForPm.setWindowTitle(QtWidgets.QApplication.translate("DetailsMainWindowForPm", "Configure Check Tool for project: ", None, -1))
        self.DetailsTabWidget.setTabText(self.DetailsTabWidget.indexOf(self.tipTab), QtWidgets.QApplication.translate("DetailsMainWindowForPm", "Tip", None, -1))
        self.DetailsTabWidget.setTabText(self.DetailsTabWidget.indexOf(self.DetailsTab), QtWidgets.QApplication.translate("DetailsMainWindowForPm", "Details", None, -1))
        self.DetailsTabWidget.setTabText(self.DetailsTabWidget.indexOf(self.checkTab), QtWidgets.QApplication.translate("DetailsMainWindowForPm", "Check Now", None, -1))
        self.prevButton.setText(QtWidgets.QApplication.translate("DetailsMainWindowForPm", "Previous", None, -1))
        self.cancelButton.setText(QtWidgets.QApplication.translate("DetailsMainWindowForPm", "Cancel", None, -1))
        self.finishButton.setText(QtWidgets.QApplication.translate("DetailsMainWindowForPm", "Finish", None, -1))

