# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\project\MindwalkToolsDevWorkspace\MindwalkTools\MayaTools\check_scene\Qt\UI\create_checker\pm_main.ui'
#
# Created: Tue Oct 31 14:42:33 2017
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_PM_View(object):
    def setupUi(self, PM_View):
        PM_View.setObjectName("PM_View")
        PM_View.resize(793, 600)
        self.centralwidget = QtWidgets.QWidget(PM_View)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.test_label = QtWidgets.QLabel(self.centralwidget)
        self.test_label.setObjectName("test_label")
        self.verticalLayout.addWidget(self.test_label)
        self.testList = QtWidgets.QListView(self.centralwidget)
        self.testList.setObjectName("testList")
        self.verticalLayout.addWidget(self.testList)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.addButton = QtWidgets.QPushButton(self.centralwidget)
        self.addButton.setObjectName("addButton")
        self.verticalLayout_3.addWidget(self.addButton)
        self.resetButton = QtWidgets.QPushButton(self.centralwidget)
        self.resetButton.setObjectName("resetButton")
        self.verticalLayout_3.addWidget(self.resetButton)
        self.removeButtion = QtWidgets.QPushButton(self.centralwidget)
        self.removeButtion.setObjectName("removeButtion")
        self.verticalLayout_3.addWidget(self.removeButtion)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.selected_label = QtWidgets.QLabel(self.centralwidget)
        self.selected_label.setObjectName("selected_label")
        self.horizontalLayout_2.addWidget(self.selected_label)
        self.project_combo = QtWidgets.QComboBox(self.centralwidget)
        self.project_combo.setObjectName("project_combo")
        self.project_combo.addItem("")
        self.horizontalLayout_2.addWidget(self.project_combo)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.selectedList = QtWidgets.QListView(self.centralwidget)
        self.selectedList.setObjectName("selectedList")
        self.verticalLayout_2.addWidget(self.selectedList)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_4.addWidget(self.line)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.nextButton = QtWidgets.QPushButton(self.centralwidget)
        self.nextButton.setObjectName("nextButton")
        self.horizontalLayout.addWidget(self.nextButton)
        self.deleteButton = QtWidgets.QPushButton(self.centralwidget)
        self.deleteButton.setObjectName("deleteButton")
        self.horizontalLayout.addWidget(self.deleteButton)
        self.cancelButton = QtWidgets.QPushButton(self.centralwidget)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        PM_View.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PM_View)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 793, 21))
        self.menubar.setObjectName("menubar")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        PM_View.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PM_View)
        self.statusbar.setObjectName("statusbar")
        PM_View.setStatusBar(self.statusbar)
        self.actionReset = QtWidgets.QAction(PM_View)
        self.actionReset.setObjectName("actionReset")
        self.actionSave_as = QtWidgets.QAction(PM_View)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionDelete = QtWidgets.QAction(PM_View)
        self.actionDelete.setObjectName("actionDelete")
        self.actionChoose = QtWidgets.QAction(PM_View)
        self.actionChoose.setObjectName("actionChoose")
        self.menuEdit.addAction(self.actionReset)
        self.menuEdit.addAction(self.actionChoose)
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(PM_View)
        QtCore.QMetaObject.connectSlotsByName(PM_View)

    def retranslateUi(self, PM_View):
        PM_View.setWindowTitle(QtWidgets.QApplication.translate("PM_View", "PM_View", None, -1))
        self.test_label.setText(QtWidgets.QApplication.translate("PM_View", "Test List:", None, -1))
        self.addButton.setText(QtWidgets.QApplication.translate("PM_View", "Add", None, -1))
        self.resetButton.setText(QtWidgets.QApplication.translate("PM_View", "Reset", None, -1))
        self.removeButtion.setText(QtWidgets.QApplication.translate("PM_View", "Remove", None, -1))
        self.selected_label.setText(QtWidgets.QApplication.translate("PM_View", "Select a project:", None, -1))
        self.project_combo.setItemText(0, QtWidgets.QApplication.translate("PM_View", "New project", None, -1))
        self.nextButton.setText(QtWidgets.QApplication.translate("PM_View", "Next", None, -1))
        self.deleteButton.setText(QtWidgets.QApplication.translate("PM_View", "Delete", None, -1))
        self.cancelButton.setText(QtWidgets.QApplication.translate("PM_View", "Cancel", None, -1))
        self.menuEdit.setTitle(QtWidgets.QApplication.translate("PM_View", "Edit", None, -1))
        self.actionReset.setText(QtWidgets.QApplication.translate("PM_View", "Reset", None, -1))
        self.actionSave_as.setText(QtWidgets.QApplication.translate("PM_View", "Save as...", None, -1))
        self.actionDelete.setText(QtWidgets.QApplication.translate("PM_View", "Delete", None, -1))
        self.actionChoose.setText(QtWidgets.QApplication.translate("PM_View", "Set Project Directory...", None, -1))

